### PR TITLE
Use filepath.Walk for deepCopy

### PR DESCRIPTION
**Pull request by abiosoft**

### CODE REVIEW

**Comment by mholt** [comment]
The reason I didn't use filepath.Walk is because it will always walk hidden directories. This PR fails when the directory has a .git folder, because it still tries to copy its contents. `.Name()` only looks at the file name, none of the parent directories. And walking the hidden folders - especially potentially large .git folders - is inefficient.

Sorry about this. I probably should have commented that in somewhere.

**Comment by abiosoft** [comment]
I think `filepath.SkipDir` can be used to achieve that. I'll modify the code.

**Comment by mholt** [comment]
Woah, I hadn't even seen that before. Sneaky std lib variables.

**Comment by mholt** [comment]
Cool, I learned something new today. Thanks!

**Pull request merged**
